python/amaranth_cfu: disable tracing in unit tests
These tests were failing because the module under test reminds you not
to leave this turned on:

    Traceback (most recent call last):
      File "/usr/local/google/home/dcallagh/work/cfu-playground/python/amaranth_cfu/test_cfu.py", line 199, in test_cfu
        self.run_sim(process, True)
      File "/usr/local/google/home/dcallagh/work/cfu-playground/python/amaranth_cfu/util.py", line 144, in run_sim
        self.fail("Simulation tracing active. "
    AssertionError: Simulation tracing active. Turn off after debugging complete.

Signed-off-by: Dan Callaghan <dcallagh@google.com>